version: '3.9'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    env_file:
      - .env